feat(KONFLUX-2072): prepare the App to be able to detect issues outside e2e workflow
redhat-appstudio-qe/ci-helper-app pull request #21
Opened 2024-02-20 08:34 UTC by dheerajodha

2024-02-20 08:57 UTC, dheerajodha commented
Related PR on the qe-tools repo: https://github.com/redhat-appstudio/qe-tools/pull/85, that adds the functionality to detect issues from outside of the e2e workflow.

2024-02-20 09:16 UTC, dheerajodha commented
_(This is what the comment looks like)_

:rotating_light: **This is a CI system failure, please consult with the QE team.**

 <details><summary>Click to view logs</summary><br><pre>[36mINFO[0m[2024-02-11T12:16:41Z] ci-operator version v20240210-10eb2346f      
[36mINFO[0m[2024-02-11T12:16:41Z] Loading configuration from https://config.ci.openshift.org for redhat-appstudio/integration-service@main 
[36mINFO[0m[2024-02-11T12:16:42Z] Resolved source https://github.com/redhat-appstudio/integration-service to main@828b9406, merging: #562 2f5b49b3 @yftacherzog 
[33mWARN[0m[2024-02-11T12:16:42Z] skipped directory "..2024_02_11_12_16_34.1237755862" when creating secret from directory "/secrets/ci-pull-credentials" 
[36mINFO[0m[2024-02-11T12:16:42Z] Requesting 4.13 from https://api.integration.openshift.com/api/upgrades_info/graph?arch=amd64&channel=fast-4.13 
[36mINFO[0m[2024-02-11T12:16:42Z] Resolved release latest to quay.io/openshift-release-dev/ocp-release@sha256:c39085b26665ed9877e208c123ff147cf7939dde4eca79a4f00fda8ea5b13dc9 
[36mINFO[0m[2024-02-11T12:16:42Z] Using namespace https://console.build02.ci.openshift.org/k8s/cluster/projects/ci-op-097gnk16 
[36mINFO[0m[2024-02-11T12:16:42Z] Running [input:root], [input:e2e-test-runner], [release:latest-integration-service-e2e], src, redhat-appstudio-integration-service-image, integration-service-e2e 
[36mINFO[0m[2024-02-11T12:16:42Z] Tagging openshift/release:golang-1.19 into pipeline:root. 
[36mINFO[0m[2024-02-11T12:16:42Z] Tagging ci/redhat-appstudio:e2e-test-runner into pipeline:e2e-test-runner. 
[36mINFO[0m[2024-02-11T12:16:42Z] Building src                                 
[36mINFO[0m[2024-02-11T12:16:42Z] Found existing build "src-amd64"             
[36mINFO[0m[2024-02-11T12:16:42Z] build didn't start running within 30m0s (phase: Pending):
Found 14 events for Pod src-amd64-build:
* 2024-02-11T12:08:46Z 2x default-scheduler: 0/19 nodes are available: 2 node(s) had untolerated taint {node-role.kubernetes.io/ci-prowjobs-worker: ci-prowjobs-worker}, 3 node(s) had untolerated taint {node-role.kubernetes.io/infra: }, 3 node(s) had untolerated taint {node-role.kubernetes.io/master: }, 4 node(s) didn't match Pod's node affinity/selector, 7 node(s) had untolerated taint {node-role.kubernetes.io/ci-tests-worker: }. no new claims to deallocate, preemption: 0/19 nodes are available: 19 Preemption is not helpful for scheduling.
* 2024-02-11T11:47:45Z 1x cluster-autoscaler: pod didn't trigger scale-up: 3 not ready for scale-up, 3 node(s) didn't match Pod's node affinity/selector, 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-tests-worker: }, 1 node(s) had untolerated taint {node-role.kubernetes.io/infra: }, 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-longtests-worker: ci-longtests-worker}, 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-prowjobs-worker: ci-prowjobs-worker}
* 2024-02-11T11:48:16Z 1x default-scheduler: 0/20 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/not-ready: }, 2 node(s) had untolerated taint {node-role.kubernetes.io/ci-prowjobs-worker: ci-prowjobs-worker}, 3 node(s) had untolerated taint {node-role.kubernetes.io/infra: }, 3 node(s) had untolerated taint {node-role.kubernetes.io/master: }, 4 node(s) didn't match Pod's node affinity/selector, 7 node(s) had untolerated taint {node-role.kubernetes.io/ci-tests-worker: }. no new claims to deallocate, preemption: 0/20 nodes are available: 20 Preemption is not helpful for scheduling.
* 2024-02-11T11:52:13Z 1x cluster-autoscaler: pod didn't trigger scale-up: 3 node(s) didn't match Pod's node affinity/selector, 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-longtests-worker: ci-longtests-worker}, 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-tests-worker: }, 1 node(s) had untolerated taint {node-role.kubernetes.io/infra: }, 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-prowjobs-worker: ci-prowjobs-worker}, 3 not ready for scale-up
* 2024-02-11T12:13:46Z 3x default-scheduler: 0/20 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/ci-longtests-worker: ci-longtests-worker}, 2 node(s) had untolerated taint {node-role.kubernetes.io/ci-prowjobs-worker: ci-prowjobs-worker}, 3 node(s) had untolerated taint {node-role.kubernetes.io/infra: }, 3 node(s) had untolerated taint {node-role.kubernetes.io/master: }, 4 node(s) didn't match Pod's node affinity/selector, 7 node(s) had untolerated taint {node-role.kubernetes.io/ci-tests-worker: }. no new claims to deallocate, preemption: 0/20 nodes are available: 20 Preemption is not helpful for scheduling.
* 2024-02-11T11:53:21Z 1x cluster-autoscaler: pod didn't trigger scale-up: 3 not ready for scale-up, 1 node(s) had untolerated taint {node-role.kubernetes.io/infra: }, 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-longtests-worker: ci-longtests-worker}, 3 node(s) didn't match Pod's node affinity/selector, 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-prowjobs-worker: ci-prowjobs-worker}, 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-tests-worker: }
* 2024-02-11T11:54:27Z 1x cluster-autoscaler: pod didn't trigger scale-up: 1 node(s) had untolerated taint {node-role.kubernetes.io/infra: }, 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-longtests-worker: ci-longtests-worker}, 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-prowjobs-worker: ci-prowjobs-worker}, 3 node(s) didn't match Pod's node affinity/selector, 3 not ready for scale-up, 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-tests-worker: }
* 2024-02-11T11:55:39Z 1x cluster-autoscaler: pod didn't trigger scale-up: 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-prowjobs-worker: ci-prowjobs-worker}, 1 node(s) had untolerated taint {node-role.kubernetes.io/infra: }, 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-tests-worker: }, 3 node(s) didn't match Pod's node affinity/selector, 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-longtests-worker: ci-longtests-worker}, 3 not ready for scale-up
* 2024-02-11T11:56:48Z 1x cluster-autoscaler: pod didn't trigger scale-up: 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-longtests-worker: ci-longtests-worker}, 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-prowjobs-worker: ci-prowjobs-worker}, 1 node(s) had untolerated taint {node-role.kubernetes.io/infra: }, 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-tests-worker: }, 3 node(s) didn't match Pod's node affinity/selector, 3 not ready for scale-up
* 2024-02-11T12:03:17Z 1x default-scheduler: 0/20 nodes are available: 1 node(s) were unschedulable, 2 node(s) had untolerated taint {node-role.kubernetes.io/ci-prowjobs-worker: ci-prowjobs-worker}, 3 node(s) had untolerated taint {node-role.kubernetes.io/infra: }, 3 node(s) had untolerated taint {node-role.kubernetes.io/master: }, 4 node(s) didn't match Pod's node affinity/selector, 7 node(s) had untolerated taint {node-role.kubernetes.io/ci-tests-worker: }. no new claims to deallocate, preemption: 0/20 nodes are available: 20 Preemption is not helpful for scheduling.
* 2024-02-11T12:05:00Z 1x cluster-autoscaler: pod didn't trigger scale-up: 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-longtests-worker: ci-longtests-worker}, 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-prowjobs-worker: ci-prowjobs-worker}, 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-tests-worker: }, 3 node(s) didn't match Pod's node affinity/selector, 3 not ready for scale-up, 1 node(s) had untolerated taint {node-role.kubernetes.io/infra: }
* 2024-02-11T12:09:39Z 1x cluster-autoscaler: pod didn't trigger scale-up: 3 not ready for scale-up, 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-prowjobs-worker: ci-prowjobs-worker}, 3 node(s) didn't match Pod's node affinity/selector, 3 node(s) had un [...]

2024-03-19 14:39 UTC, psturc requested changes
just 2 things, otherwise looks good!

2024-03-19 14:39 UTC, psturc commented on issue_comment.go
> +	targetAuthor             = "dheerajodha"
should we revert this?

2024-03-19 14:39 UTC, psturc commented on issue_comment.go
>  // JUnitTestSuites is nil.
nit: should the comment be updated?

2024-03-21 11:46 UTC, dheerajodha commented on issue_comment.go
>  // JUnitTestSuites is nil.
thanks for catching this! fixed.

2024-03-21 11:47 UTC, dheerajodha commented on issue_comment.go
> +	targetAuthor             = "dheerajodha"
oops, yes sir. fixed

2024-03-21 12:23 UTC, psturc approved these changes

2024-03-21 12:23 UTC, merged